language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"
install:
  - if [[ $TRAVIS_PYTHON_VERSION == 2.6 ]]; then pip install unittest2; fi
  - pip install .
  - pip install -r requirements.txt
script: coverage run setup.py test
after_success: coveralls
notifications:
  email:
    - hkraal@users.noreply.github.com
